/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgweyuCompany;

//
//import AgweyuCompany.ConnectionProvider.Connection; 
import java.awt.Color;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;

/**
 *
 * @author CENSUS
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        firstnametxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        SAVE = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        middlenametxt = new javax.swing.JTextField();
        emaillable = new javax.swing.JLabel();
        firstlable = new javax.swing.JLabel();
        lastlable = new javax.swing.JLabel();
        passlable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGWEYU  COLLINS & CO. ");

        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("_");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("X");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter the details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Firstname");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lastname");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        emailtxt.setText("Enter email");
        emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtxtFocusLost(evt);
            }
        });
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        emailtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailtxtKeyReleased(evt);
            }
        });

        firstnametxt.setText("Enter firstname");
        firstnametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnametxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnametxtFocusLost(evt);
            }
        });
        firstnametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstnametxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstnametxtKeyReleased(evt);
            }
        });

        lastnametxt.setText("Enter lastname");
        lastnametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnametxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnametxtFocusLost(evt);
            }
        });
        lastnametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastnametxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastnametxtKeyReleased(evt);
            }
        });

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });

        SAVE.setBackground(new java.awt.Color(0, 204, 51));
        SAVE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("CANCEL");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Middlename");

        middlenametxt.setText("Optional");
        middlenametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middlenametxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middlenametxtFocusLost(evt);
            }
        });
        middlenametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenametxtActionPerformed(evt);
            }
        });
        middlenametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                middlenametxtKeyPressed(evt);
            }
        });

        emaillable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emaillable.setForeground(new java.awt.Color(255, 102, 0));
        emaillable.setText("*");

        firstlable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstlable.setForeground(new java.awt.Color(255, 102, 0));
        firstlable.setText("*");

        lastlable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastlable.setForeground(new java.awt.Color(255, 102, 0));
        lastlable.setText("*");

        passlable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passlable.setForeground(new java.awt.Color(255, 102, 0));
        passlable.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lastnametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(firstnametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(firstlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(emaillable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lastlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(middlenametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(SAVE)
                        .addGap(76, 76, 76)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(emaillable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstlable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(middlenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastlable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passlable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(12, 12, 12))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        String email = emailtxt.getText();
        String firstname = firstnametxt.getText();
        String middlename = middlenametxt.getText();
        String lastname = lastnametxt.getText();
        String pass = password.getText();

        if (email.trim().isEmpty() || firstname.trim().isEmpty() || lastname.trim().isEmpty() || pass.trim().isEmpty()) {
            emaillable.setText("email is required");
            firstlable.setText("firstname is required");
            lastlable.setText("lastname is required");
            passlable.setText("password is required");
        } else if (email.trim().isEmpty()) {
            emaillable.setText("email is required");

        } else if (firstname.trim().isEmpty()) {
            firstlable.setText("email is required");

        } else if (lastname.trim().isEmpty()) {
            lastlable.setText("email is required");
        } else if (pass.trim().isEmpty()) {
            passlable.setText("password is required");
        } else if (!ValPassword(pass)) {

            JOptionPane.showMessageDialog(null, "the password should be atleast 8 characters with \n letters and numbers","Error", JOptionPane.ERROR_MESSAGE);

        } else if (ValidateEmail(email)) {

            if (!checkEmail(email)) {

                try {
                    String sql = "INSERT INTO `users` (`email`, `firstname`, `middlename`, `lastname`, `password`) "
                            + "VALUES ( '" + email + "', '" + firstname + "', '" + middlename + "', '" + lastname + "','" + pass + "')";
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agweyu_collins_company", "root", "");
                    Statement st = con.createStatement();
                    st.executeUpdate(sql);

                    JOptionPane.showMessageDialog(null, "you have been registered successfully");
                    setVisible(false);
                    new login().setVisible(true);

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);

                }
            }
        }
    }//GEN-LAST:event_SAVEActionPerformed

    private void emailtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusGained
        if (emailtxt.getText().equals("Enter email")) {
            emailtxt.setText("");
            emailtxt.setForeground(new Color(0, 0, 0));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_emailtxtFocusGained

    private void emailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusLost
        if (emailtxt.getText().equals("")) {
            emailtxt.setText("Enter email");
            emailtxt.setForeground(new Color(153, 153, 153));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtFocusLost

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit?", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void middlenametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenametxtActionPerformed

    private void firstnametxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnametxtFocusGained
        if (firstnametxt.getText().equals("Enter firstname")) {
            firstnametxt.setText("");
            firstnametxt.setForeground(new Color(0, 0, 0));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametxtFocusGained

    private void firstnametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnametxtFocusLost
        if (firstnametxt.getText().equals("")) {
            firstnametxt.setText("Enter firstname");
            firstnametxt.setForeground(new Color(153, 153, 153));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_firstnametxtFocusLost

    private void middlenametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenametxtFocusLost

        if (middlenametxt.getText().equals("")) {
            middlenametxt.setText("");
            middlenametxt.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_middlenametxtFocusLost

    private void lastnametxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnametxtFocusGained
        if (lastnametxt.getText().equals("Enter lastname")) {
            lastnametxt.setText("");
            lastnametxt.setForeground(new Color(0, 0, 0));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_lastnametxtFocusGained

    private void lastnametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnametxtFocusLost
        if (lastnametxt.getText().equals("")) {
            lastnametxt.setText("Enter lastname");
            lastnametxt.setForeground(new Color(153, 153, 153));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_lastnametxtFocusLost

    private void middlenametxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middlenametxtFocusGained
        if (middlenametxt.getText().equals("Optional")) {
            middlenametxt.setText("");
            middlenametxt.setForeground(new Color(0, 0, 0));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_middlenametxtFocusGained

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_passwordActionPerformed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        passlable.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyReleased

    private void lastnametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnametxtKeyReleased
        lastlable.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_lastnametxtKeyReleased

    private void firstnametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnametxtKeyReleased
        firstlable.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametxtKeyReleased

    private void emailtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtxtKeyReleased
        emaillable.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtKeyReleased

    private void firstnametxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnametxtKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //ISOControl is for edit operation(deletekey and backspace).
            firstnametxt.setEditable(true);//allows to edit if enterd character is one of the above.

        } else {
            firstnametxt.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametxtKeyPressed

    private void middlenametxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_middlenametxtKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //ISOControl is for edit operation(deletekey and backspace).
            middlenametxt.setEditable(true);//allows to edit if enterd character is one of the above.

        } else {
            middlenametxt.setEditable(false);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_middlenametxtKeyPressed

    private void lastnametxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnametxtKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //ISOControl is for edit operation(deletekey and backspace).
            lastnametxt.setEditable(true);//allows to edit if enterd character is one of the above.

        } else {
            lastnametxt.setEditable(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_lastnametxtKeyPressed

    //function to check if the email exits
    public boolean checkEmail(String email) {
        PreparedStatement pst;
        ResultSet rs;
        boolean email_exist = false;
        try {
            String query = "SELECT*FROM `users` WHERE email=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agweyu_collins_company", "root", "");
            pst = con.prepareStatement(query);
            pst.setString(1, email);
            rs = pst.executeQuery();

            if (rs.next()) {
                email_exist = true;
                JOptionPane.showMessageDialog(null, "The email used is already registerd", "Email Failed", 2);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return email_exist;
    }

    public boolean ValidateEmail(String email) {
        boolean valid_email = true;
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email))) {
            valid_email = false;
            JOptionPane.showMessageDialog(null, "please enter a valid email address", "Error", JOptionPane.ERROR_MESSAGE);
        }

        return valid_email;
    }

    public static boolean ValPassword(String password) {
        if (password.length() > 7) {
            if (checkpass(password)) {
                return true;
            } else {
                return false;
            }
        } else {
            System.out.println("too small");
            return false;
        }
    }

    public static boolean checkpass(String password) {
        boolean hasNum = false;
        boolean hasCap = false;
        boolean hasLow = false;
        char c;
        for (int i = 0; i < password.length(); i++) {
            c = password.charAt(i);
            if (Character.isDigit(c)) {
                hasNum = true;
            } else if (Character.isUpperCase(c)) {
                hasCap = true;
            } else if (Character.isLowerCase(c)) {
                hasLow = true;
            }
            if (hasCap && hasNum && hasLow) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel emaillable;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel firstlable;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastlable;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JTextField middlenametxt;
    private javax.swing.JLabel passlable;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
